name: Validate project
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
jobs:
  validate-dotnet:
    name: Validate .NET build and format
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/dotnet/sdk:8.0
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4     
      - name: Check .NET version
        run: dotnet --version       
      - name: Build .NET solution
        run: dotnet build
      - name: Check .NET code format
        run: dotnet format --verify-no-changes